---
abstract: 'Simple asynchronous ident client and server'
author:
  - 'Graham Ollis <plicease@cpan.org>'
build_requires:
  Module::Build: '0.3601'
  Test::More: '0'
configure_requires:
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AnyEvent-Ident
recommends:
  EV: '0'
requires:
  AnyEvent: '0'
  AnyEvent::Handle: '0'
  AnyEvent::Socket: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/plicease/anyevent-ident/issues
  homepage: http://perl.wdlabs.com/AnyEvent-Ident/
  repository: git://github.com/plicease/anyevent-ident.git
version: '0.06'
